# Change these first
owner: dynamicbiz4 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Trees Cafe
    url: https://treescafekandy.com
  - name: Royal Bar & Hotel
    url: https://royalbarandhotel.com
  - name: Island Canvas
    url: https://island-canvas.com
  - name: Goldan Paints
    url: https://www.goldenpaints.lk
  - name: eMatrix
    url: https://ematrixit.com/
  - name: MAD Monkey
    url: https://madmonkeystudio.com.au/
  - name: King Kandy
    url: https://kingskandy.lk/
  - name: Cyberflake
    url: https://cyberflake.biz/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hellodynamicbiz.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | Dynamic Biz
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
